# Generated by Django 4.2.1 on 2023-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_affairs', '0003_student_level_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
